name: user_database_app
description: Exploriung User Database App

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  flutter_riverpod: ^2.1.1
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  shared_preferences: ^2.0.15
  realm: ^0.11.0+rc
  get_it: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  json_serializable: ^6.5.4
  build_runner: ^2.3.2
  freezed: ^2.2.1
  flutter_gen_runner: ^5.1.0+1

flutter:
  uses-material-design: true